### PR TITLE
Fixed filtering problems & added tests

### LINKED ISSUE #407: Filtering an entity depends on the order of the fields
When filtering on one of our kinds, filter with this:
```
{
   "spec": {
     "state": "free",
     "type": {
       "kind": "machine-type",
       "uuid": "cb498080-715b-405e-8071-7e2398c2bf0f"
     }
   }
}
```

yield correct results, however, if we transpose any two lines, it fails, such as:
```
{
   "spec": {
     "type": {
       "kind": "machine-type",
       "uuid": "cb498080-715b-405e-8071-7e2398c2bf0f"
     },
    "state": "free"
   }
}
```

### PR DESCRIPTION
**Pull request by Emulebest**
resolves #407 

Added `/filter?exact=true` to preserve original exact filtering capabilities. By default this is false and asides from field order issues, adds ability to filter not necessarily specifying all fields in spec/status. E.g.

 ```
{
   "spec": {
     "state": "free",
     "type": {
       "kind": "machine-type",
       "uuid": "cb498080-715b-405e-8071-7e2398c2bf0f"
     }
   }
}
```
now also can be filtered by:
```
{
   "spec": {
     "type": {
       "kind": "machine-type",
     }
   }
}
```

### CODE REVIEW

File: papiea-engine/src/utils/utils.ts [hunk 1]
```diff
@@ -101,3 +101,26 @@ export function getRandomInt(min: number, max: number) {
...
+
+
+export function deepMerge(target: any, ...sources: any[]): any {
+    if (!sources.length) return target;
+    const source = sources.shift();
+
+    if (isObject(target) && isObject(source)) {
+        for (const key in source) {
+            if (isObject(source[key])) {
+                if (!target[key]) Object.assign(target, { [key]: {} });
```
Comment (joshua-berry-ntnx) [inline papiea-engine/src/utils/utils.ts:117]: Can't you just `target[key] = {}`? (and same below too)

File: papiea-engine/src/entity/entity_routes.ts [hunk 2]
```diff
@@ -218,3 +220,12 @@ function queryToString(q?: ExpressQueryParam): string | undefined {
             throw new BadRequestError('Invalid query parameter');
     }
 }
+
+function queryToBool(q?: ExpressQueryParam): boolean | undefined {
+    switch (typeof q) {
+        case 'string': return q === "true"
```
Comment (joshua-berry-ntnx) [inline papiea-engine/src/entity/entity_routes.ts:226]: Might want to check some other variants to be friendly to other languages ("True", "TRUE", "yes", "1", etc.)

File: papiea-engine/src/entity/entity_routes.ts [hunk 3]
```diff
@@ -27,10 +27,10 @@ export function createEntityAPIRouter(entity_api: Entity_API): Router {
         return { results: pageEntities, entity_count: totalEntities };
     }
 
-    const filterEntities = async function (user: UserAuthInfo, kind_name: string, filter: any, skip: number, size: number, sortParams?: SortParams): Promise<any> {
-        const resultSpecs: any[] = await entity_api.filter_entity_spec(user, kind_name, filter, sortParams);
+    const filterEntities = async function (user: UserAuthInfo, kind_name: string, filter: any, skip: number, size: number, exactMatch: boolean, sortParams?: SortParams): Promise<any> {
+        const resultSpecs: any[] = await entity_api.filter_entity_spec(user, kind_name, filter, exactMatch, sortParams);
```
Comment (joshua-berry-ntnx) [inline papiea-engine/src/entity/entity_routes.ts:31]:
```
style nit: You might want to consider wrapping extremely long lines which you have changed or else it might be hard for someone who is horizontally challenged to read the entire line of code that you've written
```

Comment (shlomi-nx) [reply papiea-engine/src/entity/entity_routes.ts:31]: lol, `horizontally challenged` :P
