### PR TITLE
Background task implementation

### LINKED ISSUE #582: Background/periodic task scheduling for providers
### Problem Description

There are some (perhaps many) situations where providers will need to periodically and/or proactively poll external resources to understand the current state of the world. For example, a provider which manages IoT devices may wish to poll each device to determine its health status, and then expose this information through the corresponding entity's `status` fields. Or the provider may need to periodically poll an external list of devices to determine whether any have been added or removed (such that corresponding entities can be created or deleted).

### Expected/Actual Behavior
For now I think it would be sufficient for a provider to be able to register some type of periodic task with the engine. Any such task could be run by the engine using a mechanism similar to what is done with intent handlers—that is, a single instance of a provider is chosen to run the task, and the engine monitors the task and restarts it if the instance running the task has failed. (And of course the task itself can fail, but I don't have a strong opinion on what happens then. I think it's OK not to restart it—it's already periodic anyway—or perhaps have a configurable policy for what to do in that case.)

Later, some form of work partitioning might be nice, e.g. "for all entities of kind X, periodically run task Y", and have the work monitored and appropriately divided between all instances of a provider. But I don't see an immediate need for this (and I don't think we need to go full MapReduce just yet ;) ). Just mentioning it here as something to keep in the back of our minds.

### Impact
In a non-distributed world, this could be handled by the providers themselves—e.g. through the use of interval timers, cron jobs, etc. However, providers are supposed to be stateless and horizontally scalable, and any such background task necessarily involves maintaining some state if it is long-running.

Without this feature, instances of a provider would have to coordinate amongst themselves to ensure work was not being duplicated and sub-tasks were being partitioned appropriately. One workaround might be to abuse an intent handler—for example, create a special entity with a spec/status `token` field. Have each instance try to periodically change the token's spec such that there is a diff whenever the task should be run. Then the token's intent handler would be run in a single instance chosen by the engine. The intent handler could run the task and when the task is complete, set the `status.token = spec.token`. (Of course, this assumes it's possible for a provider to proactively make calls back to the engine, which I think is possible but haven't looked into.)

<hr>
<em>Readers: If you are also experiencing this bug, please vote for it by giving the ORIGINAL POST a thumbs-up using the :smiley: button.  You are welcome to leave comments and discuss the issue if you have more details to add, but "Me too!" comments are not counted by the voting system.</em>

### PR DESCRIPTION
**Pull request by Emulebest**
resolves #582

### CODE REVIEW

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts [hunk 1]
```diff
@@ -271,6 +276,10 @@ export class ProviderSdk implements ProviderImpl {
         return this
     }
 
+    async background_task(callback: () => Promise<any>, timeout_sec: number, name: string, schema?: any): Promise<BackgroundTaskBuilder> {
```
Comment (shlomi-nx) [inline papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:279]: I'd change the order of the parameters: name, delay_sec (can this be fractional seconds?), callback, schema?)

I only put schema last because it is not mandatory. Perhaps we could remove schema from this function and add another function such as `background_task_with_schema` that has schema before the callback.

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts [hunk 2]
```diff
@@ -428,6 +437,129 @@ class Provider_Server_Manager {
...
+    private name: string
+    private kind: Kind_Builder
+    private task_entity: Entity | null = null
+    private kind_client: EntityCRUD
+    static BackgroundTaskState = class {
+        static RunningSpecState() {
+            return "Running"
+        }
+        static RunningStatusState() {
+            return "To Be Run"
```
Comment (shlomi-nx) [inline papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:453]: Minor: the strings looks reversed. Spec, which is the desire should be "Should Run" and status, which is current state, should be "Running"

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts [hunk 3]
```diff
@@ -428,6 +437,129 @@ class Provider_Server_Manager {
...
+                }
+            });
+        }
+    }
+
+    async stop_task() {
+        const states = BackgroundTaskBuilder.BackgroundTaskState
+        if (this.task_entity === null) {
+            throw new Error(`Attempting to stop missing background task on provider: 
+                            ${this.provider.get_prefix()}, ${this.provider.get_version()}`)
```
Comment (shlomi-nx) [inline papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:517]: We should also print the task name

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts [hunk 4]
```diff
@@ -428,6 +437,129 @@ class Provider_Server_Manager {
...
+        if (this.task_entity === null) {
+            this.task_entity = await this.kind_client.create({spec: {state: states.RunningSpecState()}})
+            await this.provider.provider_api_axios.patch(`${this.provider.provider_url}/${this.provider.get_prefix()}/${this.provider.get_version()}/update_status`,{
+                entity_ref: this.task_entity,
+                status: {
+                    state: states.RunningStatusState()
+                }
+            });
+        } else {
+            await this.kind_client.update(this.task_entity.metadata, {state: states.RunningSpecState()})
```
Comment (shlomi-nx) [inline papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:503]: This seems like it may be a bug. We only capture `this.task_entity` once, which means it's `metadata.spec_version` will not increase as we stop and start the task. We should probably first `get` the entity to be on the correct spec_version.

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts [hunk 5]
```diff
@@ -428,6 +437,129 @@ class Provider_Server_Manager {
...
+        const kind = provider.new_kind(schema ? this.modify_task_schema(schema) : {
+            [name]: {
+                type: "object",
+                properties: {
+                    state: {
+                        type: "string"
+                    }
+                }
+            }
+        })
```
Comment (shlomi-nx) [inline papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:482]: This seems wrong, it either takes the custom schema, or the task's schema. This should be:
```typescript
const kind = provider.new_kind({
          name: {
                type: "object",
                properties: {
                    state: {  type: "string"},
                 
                    // All here should be status-only
                    // More generic task stuff could be here (TBD), e.g.: 
                    times_called: { type: number},
                    last_error: {string},
                    last_execution_time_ms: {number},
                    average_execution_time_ms: {number},
                    etc..

                    // And for custom schema:
                    custom: schema ? this.modify_task_schema(schema) : {}  // Or simply remove custom 
                }
            }
})
```

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts [hunk 6]
```diff
@@ -428,6 +437,129 @@ class Provider_Server_Manager {
...
+            throw new Error(`Attempting to update missing background task on provider: 
+                            ${this.provider.get_prefix()}, ${this.provider.get_version()}`)
+        } else {
+            await this.provider.provider_api_axios.patch(`${this.provider.provider_url}/${this.provider.get_prefix()}/${this.provider.get_version()}/update_status`,{
+                entity_ref: this.task_entity,
+                status: {state: this.task_entity.status.state, ...status}
+            });
+        }
+    }
+}
```
Comment (shlomi-nx) [inline papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:561]: Who can use this function? If it's an API for the provider writer, this should only allow changing the `status.custom` field based on the custom schema provided.

**Review by shlomi-nx — COMMENTED** [review]
Looks good, see my comments below. I'd like to also get @joshua-berry-ntnx's opinion on this.

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 6 above)
Comment (shlomi-nx) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:561]: We can even split the background task type into two types, one for standard task without a custom schema, which would not even expose `update_status` function, and one with a custom schema that does.

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 5 above)
Comment (Emulebest) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:482]: Let's talk on that, I am not sure this is a good idea

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 6 above)
Comment (Emulebest) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:561]: Once again, let's discuss this, I am not sure that having complex interfaces for this is a very good idea

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 4 above)
Comment (Emulebest) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:503]: Yep, thought about that, will adjust

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 3 above)
Comment (Emulebest) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:517]: Sure

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 2 above)
Comment (Emulebest) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts:453]: Sounds good!

File: papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts (hunk 6 above)
Comment (shlomi-nx) [reply papiea-sdk/typescript/src/provider_sdk/typescript_sdk.ts]: Sure, we'll talk about this on our meeting today.
