### PR TITLE
issues-468: remove status-only fields from required sections of spec api

### LINKED ISSUE #468: validation should fail on `status-only` fields that are `required`
`required` in spec/status land denotes those fields in spec that the user must provide when creating an entity. When a `status-only` field is `required`, the entity cannot be created.

@joshua-berry-ntnx disagrees that `required` must only pertain to `spec` fields, and for a good reason. Having tighter schema on status as well is useful as a contract. However, this requires a more through discussion. 

We could potentially find a middle ground for now by removing required fields from the spec portion when generating the schema specs if the fields are status only.

### PR DESCRIPTION
**Pull request by NikitaChernenkoNutanix**
resolves #468 
When a field is marked as 'status-only" it doesn't appear in required fields for spec anymore

### CODE REVIEW

File: papiea-engine/src/api_docs/api_docs_generator.ts [hunk 1]
```diff
@@ -602,23 +602,64 @@ export default class ApiDocsGenerator {
...
+    /**
+     * Recursively removes a field from required if it has to be shown only for the opposite type.
+     * @param {number} schema - schema to remove the fields from.
+     * @param {number} fieldName - type of x-papiea value spec-only|status-only.
+     */
+    removeRequiredField(schema: any, fieldName: string) {
+        for (let prop in schema) {
+            // check that it's a object holding properties
+            if (typeof schema[prop] === 'object' && "required" in schema[prop] && "properties" in schema[prop]) {
+                const fieldsToRemove: String[] = []
```
Comment (Emulebest) [inline papiea-engine/src/api_docs/api_docs_generator.ts:614]: not `String[]` but `string[]`

File: papiea-engine/src/api_docs/api_docs_generator.ts [hunk 2]
```diff
@@ -602,23 +602,64 @@ export default class ApiDocsGenerator {
...
 
+    /**
+     * Recursively removes a field from required if it has to be shown only for the opposite type.
+     * @param {number} schema - schema to remove the fields from.
+     * @param {number} fieldName - type of x-papiea value spec-only|status-only.
+     */
+    removeRequiredField(schema: any, fieldName: string) {
+        for (let prop in schema) {
+            // check that it's a object holding properties
+            if (typeof schema[prop] === 'object' && "required" in schema[prop] && "properties" in schema[prop]) {
```
Comment (Emulebest) [inline papiea-engine/src/api_docs/api_docs_generator.ts:613]: I'd rather use `hasOwnProperty()` than `in` because it has more security guarantees

File: papiea-engine/src/api_docs/api_docs_generator.ts [hunk 3]
```diff
@@ -602,23 +602,64 @@ export default class ApiDocsGenerator {
...
+    }
+
     createSchema(schemas: any, kind: Kind, type: string) {
         const kindSchema: any = JSON.parse(JSON.stringify(kind.kind_structure))
         const schemaName = Object.keys(kindSchema)[0]
         if (type === "spec") {
             kindSchema[ `${ schemaName }-Spec` ] = kindSchema[ schemaName ]
             delete kindSchema[ schemaName ]
-            this.removeSchemaField(kindSchema, "status-only")
+            this.clearSchemaField(kindSchema, "status-only")
```
Comment (Emulebest) [inline papiea-engine/src/api_docs/api_docs_generator.ts:662]: See comment above please

**Review by Emulebest — CHANGES_REQUESTED** [review]
The changes are good, some minor comments. In addition, It would be beneficial if you could add the test to see that these changes don't modify `spec-only` fields that are required

File: papiea-engine/src/api_docs/api_docs_generator.ts (hunk 3 above)
Comment (Emulebest) [reply papiea-engine/src/api_docs/api_docs_generator.ts:662]: For some reason the comment regarding `clearSchemaField` wasn't saved, so posting it here.

Could we expand the function `clearSchemaField` to just 2 calls in place here? I don't see it used in any other places and the semantics of `clear` doesn't really imply removing `required` fields

File: papiea-engine/src/api_docs/api_docs_generator.ts [hunk 4]
```diff
@@ -610,11 +610,11 @@ export default class ApiDocsGenerator {
...
             // check that it's a object holding properties
-            if (typeof schema[prop] === 'object' && "required" in schema[prop] && "properties" in schema[prop]) {
-                const fieldsToRemove: String[] = []
-                const properties = schema[prop]["properties"]
+            if (typeof schema[prop] === 'object' && schema[prop].hasOwnProperty("required") && schema[prop].hasOwnProperty("properties")) {
+                const fieldsToRemove: string[] = [];
+                const properties = schema[prop]["properties"];
                 for (let name in properties) {
-                    const field = properties[name]
+                    const field = properties[name];
```
Comment (Emulebest) [inline papiea-engine/src/api_docs/api_docs_generator.ts]: really minor but we generally decided to avoid semicolon `;` in new code pieces

**Review by Emulebest — CHANGES_REQUESTED** [review]

File: papiea-engine/src/api_docs/api_docs_generator.ts (hunk 1 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/api_docs/api_docs_generator.ts]: done

File: papiea-engine/src/api_docs/api_docs_generator.ts (hunk 2 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/api_docs/api_docs_generator.ts]: done

File: papiea-engine/src/api_docs/api_docs_generator.ts (hunk 3 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/api_docs/api_docs_generator.ts]: done

File: papiea-engine/src/api_docs/api_docs_generator.ts (hunk 4 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/api_docs/api_docs_generator.ts]: done

**Review by Emulebest — APPROVED** [review]

File: papiea-engine/__tests__/docs_tests/api_docs.test.ts [hunk 5]
```diff
@@ -293,6 +293,57 @@ describe("API docs test entity", () => {
...
+
+        // add 'z' to required field, so that we check it gets removed from required and fields
+        structure.required.push("z")
+
+        // add required fields to v that are marked as status-only so that we check recursive deletion works
+        structure.properties.v.required = ["h"]
+        structure.properties.v.properties["h"] = {"type": "number", "x-papiea": "status-only"}
+
+        // set x to spec-only to see that the implementation doesn't remove it from the required fields
+        structure.properties.x["x-papiea"] = "spec-only"
```
Comment (shlomi-nx) [inline papiea-engine/__tests__/docs_tests/api_docs.test.ts:312]: There is no `spec-only` field attribute, only a `spec-only` entity. We should probably throw an error on this.

Comment (Emulebest) [reply papiea-engine/__tests__/docs_tests/api_docs.test.ts:312]: Also, I think we need to add a check that we don't have any `status-only` fields on `spec-only` entities

File: papiea-engine/__tests__/test_data_factory.ts [hunk 6]
```diff
@@ -39,6 +40,22 @@ export function getLocationDataDescription(): Data_Description {
     return randomizedLocationDataDescription;
 }
 
+export function getSpecOnlyKindDescriptionWithStatusOnlyFields(): Data_Description {
+    return getLocationDataDescription()
+}
```
Comment (Emulebest) [inline papiea-engine/__tests__/test_data_factory.ts:45]: What is the necessity for this function, isn't it an alias to `getLocationDataDescription()`?

File: papiea-engine/__tests__/test_data_factory.ts [hunk 7]
```diff
@@ -39,6 +40,22 @@ export function getLocationDataDescription(): Data_Description {
...
+    const description: any = getLocationDataDescription();
+    delete description[Object.keys(description)[0]].properties.z["x-papiea"]
+    return description
+}
+
+export function getSpecOnlyKindDescriptionWithSpecOnlyFields(): Data_Description {
+    const description: any = getLocationDataDescription();
+    description[Object.keys(description)[0]].properties.z["x-papiea"] = "spec-only"
+    return description
+}
```
Comment (Emulebest) [inline papiea-engine/__tests__/test_data_factory.ts:57]: Please use the builder pattern instead (e.g. https://github.com/nutanix/papiea/blob/7a6ac84147f379335d72a282c658651ccb129d84/papiea-engine/__tests__/test_data_factory.ts#L256), I think it is too much of little function with overly long names.

File: papiea-engine/__tests__/docs_tests/api_docs.test.ts (hunk 5 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/docs_tests/api_docs.test.ts]: I've added 2 additional steps during validation of provider:
1) check that the value of x-papiea is ["status-only'] (as these are all possible values for now)
2) check that if an entity is a spec-only entity, x-papiea can be only one of [""] (as these are all possible values except status-only)

File: papiea-engine/__tests__/test_data_factory.ts [hunk 8]
```diff
@@ -90,6 +107,22 @@ export function getSpecOnlyKind(): SpecOnlyEntityKind {
...
+        kind_structure: desc,
+        intentful_signatures: [],
+        dependency_tree: new Map(),
+        kind_procedures: {},
+        entity_procedures: {},
+        differ: undefined,
+        intentful_behaviour: IntentfulBehaviour.SpecOnly
+    };
+    return locationKind;
+}
```
Comment (Emulebest) [inline papiea-engine/__tests__/test_data_factory.ts:124]: see the comment above

File: papiea-engine/__tests__/validation_tests/validation.test.ts [hunk 9]
```diff
@@ -205,4 +210,31 @@ describe("Validation tests", () => {
...
+        }).toThrow()
+    })
+
+    test("Validator validate correct spec only kind structure", async () => {
+        expect.assertions(1)
+        const desc = getSpecOnlyKindDescription()
+        const kindStructure = desc[Object.keys(desc)[0]]
+        expect(() => {
+            validator.validateKindStructure(kindStructure)
+        }).not.toThrow()
```
Comment (Emulebest) [inline papiea-engine/__tests__/validation_tests/validation.test.ts:238]: Nitpicking, but `.not.toThrow()` could be expressed without any expects

File: papiea-engine/src/validator/index.ts [hunk 10]
```diff
@@ -134,9 +143,49 @@ export class ValidatorImpl {
...
+            Object.values(kind.kind_structure).forEach(structure => {
+                this.validateKindStructure(structure)
+            })
         })
     }
 
+    validateKindStructure(schema: Data_Description) {
+        const xPapieaField = "x-papiea"
+        const statusOnlyValue = "status-only"
+        // xPapieaField pryoperty have only statusOnlyValue value
```
Comment (Emulebest) [inline papiea-engine/src/validator/index.ts:155]: typo

File: papiea-engine/src/validator/index.ts [hunk 11]
```diff
@@ -134,9 +143,49 @@ export class ValidatorImpl {
...
+                            message: `${fieldName} has wrong value: ${xPapieaValue}, possible values are: ${possibleValues.toString()}`
+                        }])
+                    }
+                } else {
+                    this.validateFieldValue(schema[prop], fieldName, possibleValues)
+                }
+
+            }
+        }
+    }
```
Comment (Emulebest) [inline papiea-engine/src/validator/index.ts:177]: This one is good! I would change the name of the function to `validateXPapieaMark` or similar, since `validateFieldValue` is too general for what this function does

File: papiea-engine/src/validator/index.ts [hunk 12]
```diff
@@ -134,9 +143,49 @@ export class ValidatorImpl {
...
             })
+            Object.values(kind.kind_structure).forEach(structure => {
+                this.validateKindStructure(structure)
+            })
         })
     }
 
+    validateKindStructure(schema: Data_Description) {
+        const xPapieaField = "x-papiea"
+        const statusOnlyValue = "status-only"
```
Comment (Emulebest) [inline papiea-engine/src/validator/index.ts:154]: If these are constant, I'd rather add a constant or enum (choose appropriate) for these field names

File: papiea-engine/src/validator/index.ts [hunk 13]
```diff
@@ -134,9 +143,49 @@ export class ValidatorImpl {
...
+                }
+
+            }
+        }
+    }
+
+    validateSpecOnlyStructures(entity: Data_Description) {
+        const specOnlyValue = "spec-only"
+        const xPapieaEntityField = "x-papiea-entity"
+        const xPapieaField = "x-papiea"
```
Comment (Emulebest) [inline papiea-engine/src/validator/index.ts:182]: Same as above

File: papiea-engine/__tests__/validation_tests/validation.test.ts [hunk 14]
```diff
@@ -205,4 +210,31 @@ describe("Validation tests", () => {
             validator.validate_uuid(kind_with_pattern, id)
         }).toThrow()
     });
+
+    test("Validator validate spec only kind structure with spec-only value x-papiea field", async () => {
```
Comment (Emulebest) [inline papiea-engine/__tests__/validation_tests/validation.test.ts:214]: should it pass, should it fail? Hard to wrap the head around :). Please add the expected outcome

File: papiea-engine/__tests__/validation_tests/validation.test.ts [hunk 15]
```diff
@@ -205,4 +210,31 @@ describe("Validation tests", () => {
...
+        expect.assertions(1)
+        const desc = getSpecOnlyKindDescriptionWithSpecOnlyFields()
+        const kindStructure = desc[Object.keys(desc)[0]]
+        expect(() => {
+            validator.validateKindStructure(kindStructure)
+        }).toThrow()
+    })
+
+    test("Validator validate spec only kind structure with status-only value x-papiea field", async () => {
```
Comment (Emulebest) [inline papiea-engine/__tests__/validation_tests/validation.test.ts:223]: Same as above

File: papiea-engine/__tests__/validation_tests/validation.test.ts [hunk 16]
```diff
@@ -205,4 +210,31 @@ describe("Validation tests", () => {
...
+        expect.assertions(1)
+        const desc = getSpecOnlyKindDescriptionWithStatusOnlyFields()
+        const kindStructure = desc[Object.keys(desc)[0]]
+        expect(() => {
+            validator.validateKindStructure(kindStructure)
+        }).toThrow()
+    })
+
+    test("Validator validate correct spec only kind structure", async () => {
```
Comment (Emulebest) [inline papiea-engine/__tests__/validation_tests/validation.test.ts:232]: Same as above

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts [hunk 17]
```diff
@@ -63,6 +68,48 @@ describe("Provider API tests", () => {
...
+        const kind = getSpecOnlyKindByDescription(desc)
+        const provider: any = {
+            version: providerVersion,
+            prefix: providerPrefix,
+            kinds: [kind],
+            procedures: {},
+            extension_structure: {},
+            allowExtraProps: false
+        };
+        providerApi.post('/', provider).then((e) => done.fail()).catch(() => done());
```
Comment (Emulebest) [inline papiea-engine/__tests__/provider_tests/provider_api.test.ts:82]: Please use the `try catch(e)` or `expect.toThrow` format in new code, thanks

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts [hunk 18]
```diff
@@ -63,6 +68,48 @@ describe("Provider API tests", () => {
...
+        const kind = getSpecOnlyKindByDescription(desc)
+        const provider: any = {
+            version: providerVersion,
+            prefix: providerPrefix,
+            kinds: [kind],
+            procedures: {},
+            extension_structure: {},
+            allowExtraProps: false
+        };
+        providerApi.post('/', provider).then(() => done.fail()).catch(() => done());
```
Comment (Emulebest) [inline papiea-engine/__tests__/provider_tests/provider_api.test.ts:96]: Please use the try catch(e) or expect.toThrow format in new code, thanks

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts [hunk 19]
```diff
@@ -63,6 +68,48 @@ describe("Provider API tests", () => {
...
+        const kind = getSpecOnlyKindByDescription(desc)
+        const provider: Provider = {
+            version: providerVersion,
+            prefix: providerPrefix,
+            kinds: [kind],
+            procedures: {},
+            extension_structure: {},
+            allowExtraProps: false
+        };
+        providerApi.post('/', provider).then(() => done()).catch(() => done.fail());
```
Comment (Emulebest) [inline papiea-engine/__tests__/provider_tests/provider_api.test.ts:110]: Please use the try catch(e) or expect.toThrow format in new code, thanks

File: papiea-engine/src/validator/index.ts (hunk 12 above)
Comment (Emulebest) [reply papiea-engine/src/validator/index.ts:154]: Possible values should be a data structure of its own (array, enum, etc.)

File: papiea-engine/src/validator/index.ts [hunk 20]
```diff
@@ -134,9 +143,49 @@ export class ValidatorImpl {
...
+                    }
+                } else {
+                    this.validateFieldValue(schema[prop], fieldName, possibleValues)
+                }
+
+            }
+        }
+    }
+
+    validateSpecOnlyStructures(entity: Data_Description) {
```
Comment (Emulebest) [inline papiea-engine/src/validator/index.ts:179]: `validateSpecOnlyStructure` (without letter S, since we are not working with collections here)
This is not a very good OOP practice, since it is very specific, but I think that we could leave that for now. Maybe we could rethink this as we have more cases like `spec-only` stuff

**Review by Emulebest — CHANGES_REQUESTED** [review]
Overall, changes are good, some code style comments

File: papiea-engine/__tests__/test_data_factory.ts (hunk 6 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/test_data_factory.ts:45]: getLocationDataDescription() provides incorrect structure - spec-only entity with status-only fields.
I'd refactor it to correct structure, but it's used throughout the project so I decided to make it obvious what kind of data is provided by the function.

File: papiea-engine/src/validator/index.ts (hunk 11 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/validator/index.ts:177]: the function is currently abstract and is not bound to a specific field and specific possible values, I'd keep it as it is as it can't be reused so.

File: papiea-engine/__tests__/validation_tests/validation.test.ts (hunk 15 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/validation_tests/validation.test.ts:223]: will do

File: papiea-engine/__tests__/validation_tests/validation.test.ts (hunk 16 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/validation_tests/validation.test.ts:232]: will do

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts (hunk 17 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/provider_tests/provider_api.test.ts:82]: will do

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts (hunk 18 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/provider_tests/provider_api.test.ts:96]: will do

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts (hunk 19 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/provider_tests/provider_api.test.ts:110]: will do

File: papiea-engine/src/validator/index.ts (hunk 20 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/validator/index.ts:179]: I'm open to alternative approaches to the function. We have a specific logic for spec-only structures so it seems to be an easy solution for now.

File: papiea-engine/__tests__/test_data_factory.ts (hunk 6 above)
Comment (Emulebest) [reply papiea-engine/__tests__/test_data_factory.ts:45]: I see... This should be handled. Since updating the status of `spec-only` entity is already an error, then I'd remove the
```
    z:
      type: number
      x-papiea: status-only
```
and see if tests do fail. I don't think many will do

File: papiea-engine/src/validator/index.ts (hunk 11 above)
Comment (Emulebest) [reply papiea-engine/src/validator/index.ts:177]: The problem is that the function doesn't validate the value itself, it only validates the entity sort of metadata portion (`x-papiea` stuff)

File: papiea-engine/__tests__/test_data_factory.ts (hunk 7 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/test_data_factory.ts:57]: we have withKinds in the builder already. we need to provide the appropriate kind to it.
in order to do so, I introduced 
https://github.com/nutanix/papiea/blob/issue-468-spec-remove-status-only-fields-from-required/papiea-engine/__tests__/test_data_factory.ts#L110
and https://github.com/nutanix/papiea/blob/issue-468-spec-remove-status-only-fields-from-required/papiea-engine/__tests__/test_data_factory.ts#L81

Comment (Emulebest) [reply papiea-engine/__tests__/test_data_factory.ts:57]: related to #492

File: papiea-engine/__tests__/test_data_factory.ts (hunk 6 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/test_data_factory.ts]: thanks for resolving it!

File: papiea-engine/__tests__/test_data_factory.ts (hunk 7 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/test_data_factory.ts]: Seems like a good solution

File: papiea-engine/__tests__/validation_tests/validation.test.ts (hunk 14 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/validation_tests/validation.test.ts]: done

File: papiea-engine/__tests__/validation_tests/validation.test.ts (hunk 16 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/validation_tests/validation.test.ts]: done

File: papiea-engine/__tests__/validation_tests/validation.test.ts (hunk 15 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/validation_tests/validation.test.ts]: done

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts (hunk 19 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/provider_tests/provider_api.test.ts]: done

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts (hunk 18 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/provider_tests/provider_api.test.ts]: done

File: papiea-engine/__tests__/provider_tests/provider_api.test.ts (hunk 17 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/__tests__/provider_tests/provider_api.test.ts]: done

File: papiea-engine/src/validator/index.ts (hunk 11 above)
Comment (NikitaChernenkoNutanix) [reply papiea-engine/src/validator/index.ts]: renamed xPapieaValue to value, changed camelCase to snake_case

File: papiea-engine/src/validator/index.ts (hunk 12 above)
Comment (Emulebest) [reply papiea-engine/src/validator/index.ts]: Since there is only one case for now `status-only` let's leave it as is

File: papiea-engine/src/validator/index.ts (hunk 11 above)
Comment (Emulebest) [reply papiea-engine/src/validator/index.ts]: Since function doesn't feature `xPapiea...` stuff, we can assume it is general enough

**Review by Emulebest — APPROVED** [review]
